import { GestureType, ActionType } from '../types/gesture';
import type { Gesture } from '../types/gesture';

export const PRESET_GESTURES: Gesture[] = [
  {
    id: 'swipe-left',
    name: 'Swipe Left',
    type: 'swipe',
    direction: 'left',
    handPose: GestureType.SWIPE_LEFT,
    action: { type: ActionType.CHROME, value: 'goBack' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.8,
    cooldown: 300,
    feedback: { sound: true, visual: true },
  },
  {
    id: 'swipe-right',
    name: 'Swipe Right',
    type: 'swipe',
    direction: 'right',
    handPose: GestureType.SWIPE_RIGHT,
    action: { type: ActionType.CHROME, value: 'goForward' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.8,
    cooldown: 300,
    feedback: { sound: true, visual: true },
  },
  {
    id: 'swipe-up',
    name: 'Swipe Up',
    type: 'swipe',
    direction: 'up',
    handPose: GestureType.SWIPE_UP,
    action: { type: ActionType.CHROME, value: 'scrollUp' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.8,
    cooldown: 300,
    feedback: { sound: true, visual: true },
  },
  {
    id: 'swipe-down',
    name: 'Swipe Down',
    type: 'swipe',
    direction: 'down',
    handPose: GestureType.SWIPE_DOWN,
    action: { type: ActionType.CHROME, value: 'scrollDown' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.8,
    cooldown: 300,
    feedback: { sound: true, visual: true },
  },
  {
    id: 'pinch',
    name: 'Pinch',
    type: 'static',
    handPose: GestureType.PINCH,
    action: { type: ActionType.CHROME, value: 'zoomIn' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.75,
    cooldown: 500,
    feedback: { sound: true, visual: true, haptic: true },
  },
  {
    id: 'spread',
    name: 'Spread',
    type: 'static',
    handPose: GestureType.SPREAD,
    action: { type: ActionType.CHROME, value: 'zoomOut' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.75,
    cooldown: 500,
    feedback: { sound: true, visual: true, haptic: true },
  },
  {
    id: 'fist',
    name: 'Fist',
    type: 'static',
    handPose: GestureType.FIST,
    action: { type: ActionType.CHROME, value: 'closeTab' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.85,
    cooldown: 500,
    feedback: { sound: true, visual: true, haptic: true },
  },
  {
    id: 'open-palm',
    name: 'Open Palm',
    type: 'static',
    handPose: GestureType.OPEN_PALM,
    action: { type: ActionType.CHROME, value: 'newTab' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.85,
    cooldown: 500,
    feedback: { sound: true, visual: true },
  },
  {
    id: 'thumbs-up',
    name: 'Thumbs Up',
    type: 'static',
    handPose: GestureType.THUMBS_UP,
    action: { type: ActionType.CHROME, value: 'bookmark' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.85,
    cooldown: 500,
    feedback: { sound: true, visual: true },
  },
  {
    id: 'thumbs-down',
    name: 'Thumbs Down',
    type: 'static',
    handPose: GestureType.THUMBS_DOWN,
    action: { type: ActionType.CHROME, value: 'removeBookmark' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.85,
    cooldown: 500,
    feedback: { sound: true, visual: true },
  },
  {
    id: 'point',
    name: 'Point',
    type: 'static',
    handPose: GestureType.POINT,
    action: { type: ActionType.CHROME, value: 'moveCursor' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.8,
    cooldown: 100,
    feedback: { visual: true },
  },
  {
    id: 'peace',
    name: 'Peace Sign',
    type: 'static',
    handPose: GestureType.PEACE,
    action: { type: ActionType.CHROME, value: 'refresh' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.85,
    cooldown: 500,
    feedback: { sound: true, visual: true },
  },
  {
    id: 'wave',
    name: 'Wave',
    type: 'dynamic',
    handPose: GestureType.WAVE,
    action: { type: ActionType.CHROME, value: 'toggleExtension' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.7,
    cooldown: 800,
    feedback: { sound: true, visual: true },
  },
  {
    id: 'rotate',
    name: 'Rotate',
    type: 'dynamic',
    direction: 'clockwise',
    handPose: GestureType.ROTATE,
    action: { type: ActionType.CHROME, value: 'zoomOut' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.7,
    cooldown: 500,
    feedback: { sound: true, visual: true, haptic: true },
  },
  {
    id: 'ok-sign',
    name: 'OK Sign',
    type: 'static',
    handPose: GestureType.OK_SIGN,
    action: { type: ActionType.CHROME, value: 'toggleExtension' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.8,
    cooldown: 800,
    feedback: { sound: true, visual: true, haptic: true },
  },
  {
    id: 'rock',
    name: 'Rock Sign',
    type: 'static',
    handPose: GestureType.ROCK,
    action: { type: ActionType.SHORTCUT, value: 'Ctrl+Shift+G' },
    isEnabled: true,
    isPreset: true,
    confidence: 0.8,
    cooldown: 500,
    feedback: { sound: true, visual: true },
  },
];
